services:
  - type: web
    name: suvarn-bachat-yojana
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend --include=dev && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_API_BASE_URL
        value: /api
    autoDeploy: true
